
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: vote
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi   # Must match PV capacity
  selector:
    matchLabels:
      app: postgres  # Binds to PV with this label
  volumeName: postgres-local-pv  # Explicitly targets our PV