---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-local-pv
  namespace: vote
  labels:
    app: postgres
    type: local
spec:
  capacity:
    storage: 1Gi   # Adjust size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Keeps data after PVC deletion
  local:
    path: /home/luffy/test/a  # Directory on your node

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: vote
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi   # Must match PV capacity
  selector:
    matchLabels:
      app: postgres  # Binds to PV with this label
  volumeName: postgres-local-pv  # Explicitly targets our PV