apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-local-pv
  namespace: vote
  labels:
    app: postgres
    type: local
spec:
  capacity:
    storage: 1Gi   # Adjust size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Keeps data after PVC deletion
  local:
    path: /home/luffy/test/a  # Directory on your node
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube  # Replace with actual node name (use `kubectl get nodes`)