apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-local-pv
  labels:
    app: postgres
    type: local
spec:
  storageClassName: ""  # Explicitly empty to avoid default SC
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /home/luffy/test/a  # Your specified path
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - minikube  # Matches Minikube node name